//
//  WalletTransactionType.swift
//  CoffeeCraft
//
//  Created by Sok Pich on 3/3/26.
//

import FirebaseFirestore
//
//  WalletTransaction.swift
//  CoffeeCraft
// import Foundation
import SwiftUI

// MARK: - WalletTransactionType
// The four possible transaction types in the wallet ledger.
// Stored in Firestore as a raw String value.

enum WalletTransactionType: String, Codable, CaseIterable {
    case topup   = "topup"    // User manually added $
    case payment = "payment"  // $ deducted when order was placed
    case refund  = "refund"   // $ returned when order was cancelled
    case reward  = "reward"   // Bonus $ from loyalty milestone

    // MARK: Display

    var displayName: String {
        switch self {
        case .topup:   return "Top-Up"
        case .payment: return "Payment"
        case .refund:  return "Refund"
        case .reward:  return "Reward"
        }
    }

    /// SF Symbol icon for each type — used in WalletTransactionRow
    var icon: String {
        switch self {
        case .topup:   return "arrow.down.circle.fill"
        case .payment: return "cart.fill"
        case .refund:  return "arrow.uturn.left.circle.fill"
        case .reward:  return "star.fill"
        }
    }

    /// Color tint for the icon — green for credits, red for debits
    var color: Color {
        switch self {
        case .topup:   return .semanticSuccess
        case .payment: return .semanticError
        case .refund:  return Color("activeTF")
        case .reward:  return Color.accentGold
        }
    }
}

// MARK: - WalletTransaction
// Represents a single immutable ledger entry in Firestore.
// Collection: "wallet_transactions"
// Document ID: auto-generated by Firestore
//
// FIRESTORE SHAPE:
// /wallet_transactions/<AUTO_ID>
// {
//   "userId":        "UID_ABC123",
//   "type":          "payment",
//   "amount":        -12.50,       ← positive = credit, negative = debit
//   "balanceBefore": 100.0,
//   "balanceAfter":  87.50,
//   "description":   "Order #xK9pQ2",
//   "referenceId":   "xK9pQ2",     ← optional, orderId for payment/refund
//   "timestamp":     <Timestamp>
// }
//
// NOTE: wallet_transactions are WRITE-ONCE. Never update an existing transaction.
// If something needs to be reversed, a new "refund" transaction is written instead.

struct WalletTransaction: Identifiable, Codable {

    // MARK: - Stored Properties

    @DocumentID var id: String?
    let userId: String
    let type: WalletTransactionType
    let amount: Double              // + credit  /  − debit
    let balanceBefore: Double       // Snapshot of balance before this tx
    let balanceAfter: Double        // Snapshot of balance after this tx
    let description: String         // Human-readable label
    let referenceId: String?        // orderId for payment / refund types
    let timestamp: Date

    // MARK: - Computed Helpers

    /// True if this transaction added $ to the wallet
    var isCredit: Bool { amount > 0 }

    /// Formatted amount with sign — e.g. "+$10" or "-$12.5"
    var formattedAmount: String {
        let sign = isCredit ? "+" : ""
        return "\(sign)\(amount.currencyFormatted)"
    }

    /// Short timestamp label — e.g. "Jan 5, 2:30 PM"
    var formattedDate: String {
        timestamp.formatted(date: .abbreviated, time: .shortened)
    }
}

// MARK: - WalletTransaction + Factory
extension WalletTransaction {

    /// Builds a dictionary ready to be written to Firestore.
    /// Called inside WalletService runTransaction() closures.
    func toFirestoreData() -> [String: Any] {
        var data: [String: Any] = [
            Firebase.WalletTransactions.userId:        userId,
            Firebase.WalletTransactions.type:          type.rawValue,
            Firebase.WalletTransactions.amount:        amount,
            Firebase.WalletTransactions.balanceBefore: balanceBefore,
            Firebase.WalletTransactions.balanceAfter:  balanceAfter,
            Firebase.WalletTransactions.description:   description,
            Firebase.WalletTransactions.timestamp:     Timestamp(date: timestamp)
        ]
        if let referenceId { data[Firebase.WalletTransactions.referenceId] = referenceId }
        return data
    }
}
